name: Build & publish Docker Image
run-name: "${{ github.event.inputs.git_tag }}: build & publish"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name output
        id: tagname
        run: |
          if [[ -n "${{ github.event.inputs.git_tag }}" ]]; then
            TAG_NAME="${{ github.event.inputs.git_tag }}"
          else
            TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          fi
          echo "::set-output name=tagname::$TAG_NAME"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.tagname.outputs.tagname }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/alileza/alert-relabeller:${{ steps.tagname.outputs.tagname }}
```